Updated lumina-fm man page
trueos/lumina-docs pull request #53
Opened 2017-10-31 18:15 UTC by a-stjohn

2017-10-31 18:28 UTC, a-stjohn commented
I noticed I didn't add "Ar" before "FILE" in the synopsis.

2017-11-01 13:22 UTC, Mrt134 requested changes
Added notes for the changes you mentioned were missing, plus a couple minor text reworks.

2017-11-01 13:22 UTC, Mrt134 commented on manpages/lumina-fm.8
> +.Op FILE
Needs Ar before FILE -> .Op Ar FILE

2017-11-01 13:22 UTC, Mrt134 commented on manpages/lumina-fm.8
> +If no argument or file path is specified, the command will open the
...the command will open... -> the command opens

2017-11-01 13:22 UTC, Mrt134 commented on manpages/lumina-fm.8
Needs an .El entry to close list.

2017-11-01 13:22 UTC, Mrt134 commented on manpages/lumina-fm.8
> +
Needs .El entry to close list.

2017-11-02 13:26 UTC, Mrt134 approved these changes

2017-11-02 13:26 UTC, merged